# Set up application configuration constants for the current
# environment.

development:
  host: molehill-dev
  google_analytics_code: ~

test:
  host: example.com
  google_analytics_code: ~

cucumber:
  host: example.com
  google_analytics_code: ~

production:
#  host: 
#  google_tracking_code: UA-12345-67
